name: build
on:
  push:
  pull_request:

jobs:
  plugin_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        ver: [1.3.5, 1.20.0, 1.28.0]
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18'
      - name: asdf_plugin_test
        uses: asdf-vm/actions/plugin-test@v1
        with:
          version: ${{ matrix.ver }}
          command: swagger version
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
